language: python

python:
    - "3.6"
    - "3.7"

services:
    - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - flask db upgrade

script:
  - pytest -v
