"""empty message

Revision ID: 4d3be225f5a9
Revises: b40bdeec3e0a
Create Date: 2020-08-15 19:44:50.096231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3be225f5a9'
down_revision = 'b40bdeec3e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'username')
    # ### end Alembic commands ###
