"""Initial migration

Revision ID: 714aeb6964e5
Revises: 
Create Date: 2020-05-03 15:57:15.752783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714aeb6964e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PROGRAMMING', 'ART', 'MUSIC', 'MODELING', 'GAMEDEV', name='challengetype'), nullable=False),
    sa.Column('title', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('wp_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('evaluation_note', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('challenge_requirement')
    op.drop_table('challenge')
    # ### end Alembic commands ###
