"""empty message

Revision ID: b40bdeec3e0a
Revises: 714aeb6964e5
Create Date: 2020-05-07 01:25:43.060848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40bdeec3e0a'
down_revision = '714aeb6964e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('published', sa.DateTime(), nullable=True))
    op.add_column('submission', sa.Column('submitted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'submitted')
    op.drop_column('challenge', 'published')
    # ### end Alembic commands ###
